### ISSUE TITLE
Didn't run on Ubuntu

### ISSUE THREAD

**Issue by suchitsha** [SerpentAI/sneakysnek#2]
Traceback (most recent call last):
  File "Training Data Collection/caputre_training_date.py", line 1, in <module>
    from sneakysnek.recorder import Recorder
  File "/home/dao/.local/lib/python2.7/site-packages/sneakysnek/recorder.py", line 26
    raise RecorderError(f"Unsupported platform '{sys.platform}'")
                                                               ^
SyntaxError: invalid syntax

-----------------------------------------------------------------------------------
Could it be as Ubuntu returns   'linux2' for sys.platform while expected is "linux2" ?

**Comment by nbrochu** [comment]
The invalid syntax is because you aren't running on Python 3.6+

The platform for Ubuntu is covered: https://github.com/SerpentAI/sneakysnek/blob/master/sneakysnek/recorder.py#L16

**Comment by suchitsha** [comment]
Thanks!
